site_name: Ingresso.com
repo_url: https://github.com/Requisitos-de-Software/2021.1-Grupo01

theme:
  name: material
  features: navigation.tabs

nav:
  - Inicio: "index.md"
  - Planejamento: "planejamento/index.md"
